name: Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Run isort
        run: poetry run isort --check-only --diff .

      - name: Run black
        run: poetry run black --check .

      # - name: Run tests
      #   run: poetry run pytest

      - name: Build package
        run: poetry build

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/*.whl

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t baichuan_api .
